version: "2.8"

services:
      security_service_postgres:
            image: postgres
            restart: always
            environment:
                  POSTGRES_HOST_AUTH_METHOD: trust
            expose:
                  - 5436
            ports:
                  - 5436:5436
            command: -p 5436
            volumes:
                  - ~/databases/security:/var/lib/postgresql/data      
      security_service_postgres:
            image: redis:latest
            restart: always
            environment:
                  ALLOW_EMPTY_PASSWORD: "yes"
            expose:
                  - 6380
            ports:
                  - 6380:6380
            command: "--port 6380"
            volumes:
                  - ~/databases/redis:/data
                  - ~/databases/redis:/var/lib/redis
                  - ~/databases/redis:/usr/local/etc/redis/redis.conf

                  