// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/99designs/gqlgen/graphql"
)

type Notification struct {
	ID      int    `json:"id"`
	IsLike  bool   `json:"IsLike"`
	LikerID int    `json:"LikerId"`
	PostID  int    `json:"PostId"`
	Seen    bool   `json:"Seen"`
	Time    string `json:"Time"`
}

type UpdateUserInput struct {
	Name   string          `json:"name"`
	Gender string          `json:"gender"`
	Avatar *graphql.Upload `json:"avatar"`
}

type User struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	IsFollowing bool   `json:"isFollowing"`
	Avatar      string `json:"avatar"`
}

type UserInput struct {
	Name     string          `json:"name"`
	Email    string          `json:"email"`
	Gender   string          `json:"gender"`
	Password string          `json:"password"`
	Avatar   *graphql.Upload `json:"avatar"`
}

type CreatePostInput struct {
	Title  string          `json:"title"`
	Body   string          `json:"body"`
	Image1 *graphql.Upload `json:"image1"`
	Image2 *graphql.Upload `json:"image2"`
	Image3 *graphql.Upload `json:"image3"`
	Image4 *graphql.Upload `json:"image4"`
}

type DeletePostInput struct {
	PostID int `json:"postId"`
}

type Post struct {
	Title       string   `json:"title"`
	Body        string   `json:"body"`
	ID          int      `json:"id"`
	OwnerID     int      `json:"ownerId"`
	IsLiked     bool     `json:"isLiked"`
	Likes       int      `json:"likes"`
	User        *User    `json:"user"`
	PictureUrls []string `json:"pictureUrls"`
}

type Session struct {
	Device    string `json:"device"`
	CreatedAt int    `json:"createdAt"`
	SessionID int    `json:"sessionId"`
}
