// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Gender string `json:"gender"`
}

type CreatePostInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Gender   string `json:"gender"`
	Password string `json:"password"`
}

type DeletePostInput struct {
	PostID int `json:"postId"`
}

type GetPostInput struct {
	PostIds []int `json:"postIds"`
}

type Post struct {
	Title   string `json:"title"`
	Body    string `json:"body"`
	ID      int    `json:"id"`
	OwnerID int    `json:"ownerId"`
}

type Session struct {
	Device    string `json:"device"`
	CreatedAt int    `json:"createdAt"`
	SessionID int    `json:"sessionId"`
}
