// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Notification struct {
	ID      int    `json:"id"`
	IsLike  bool   `json:"IsLike"`
	LikerID int    `json:"LikerId"`
	PostID  int    `json:"PostId"`
	Seen    bool   `json:"Seen"`
	Time    string `json:"Time"`
}

type User struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Email       string `json:"email"`
	Gender      string `json:"gender"`
	IsFollowing bool   `json:"isFollowing"`
}

type CreatePostInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Gender   string `json:"gender"`
	Password string `json:"password"`
}

type DeletePostInput struct {
	PostID int `json:"postId"`
}

type Post struct {
	Title   string `json:"title"`
	Body    string `json:"body"`
	ID      int    `json:"id"`
	OwnerID int    `json:"ownerId"`
	IsLiked bool   `json:"isLiked"`
	Likes   int    `json:"likes"`
	User    *User  `json:"user"`
}

type Session struct {
	Device    string `json:"device"`
	CreatedAt int    `json:"createdAt"`
	SessionID int    `json:"sessionId"`
}
