version: "2.8"

services:
      db_postgres:
            image: postgres
            restart: always
            environment:
                  POSTGRES_PASSWORD: 1
            expose:
                  - "5433"
            ports:
                  - "5433:5433"
            command: -p 5433
