version: "2.8"

services:
      notification_service_postgres:
            image: postgres
            restart: always
            environment:
                  POSTGRES_HOST_AUTH_METHOD: trust
            expose:
                  - 5437
            ports:
                  - 5437:5437
            command: -p 5437
            volumes:
                  - ~/databases/notification:/var/lib/postgresql/data
